# Welcome to Jekyll!
# 
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: <span>identex</span>
email: contact@identex.co
description: >- # this means to ignore newlines until "baseurl:"
  <a href="https://identex.co">identex</a> is a tool to help protect and grow your local business.
baseurl: "" # the subpath of your site and 7, e.g. baseurl: "blog/"
url: "https://knowledge.identex.co" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: "<!--more-->"

#Use statically.io to serve images
cdnurl: "https://cdn.statically.io/img/jorigamy.github.io"
statically: 'no'


#Permalinks

#permalink: /:title/
#permalink: /:categories/:title/
#permalink: /:year/:month/:day/:title.html

#Finding solution for pagination, now is disabled
# paginate: 6

# Site settings

logo: /assets/images/identex/INDENTEX-JUST-LOGO-black.png
favicon: https://cdn.statically.io/favicons/jekyllrb.com
navbar-logo: identex/INDENTEX-JUST-LOGO-black.svg

author :
  name : identex
  email : contact@identex.co
  github : identex
  twitter : identexco
  facebook: 
  linkedin: 
  instagram: identex.co
  pinterest: 
  google: 
  feedburner :
  angellist: narc-identex

# Fuck tracking. All my homies hate tracking.
#google :
#    tracking_id : 'UA-109407288-1' # Id google analitics
#    optimize_id : 'GTM-MPKVJB9' # I'id di google optimize per A/B Testing
#    tagmanager_id: 'GTM-5VNXBR4' # id di google tag manager
#    ad_client: 'ca-pub-9204963049240271' # id google ADsense (to edit other id's of google ADsense go to /_includes/JB/ads-block-html )

# If we want to enable comments
#disqus :
#    short_name : identex
    # how to use
    #      {% if site.disqus.short_name %}
    #        {% include JB/disqus.html %}
    #      {% endif %}


# data for jekyll-seo-tags plugins
social:
  name: identex KB
  links:
    - https://twitter.com/identexco
    - https://github.com/identex
twitter:
  username: identexco

# Fuck tracking. All my homies hate tracking.
#facebook:
# app_id: 509727322725898 #the app id from https://developers.facebook.com/
# admins: 1010094929028825 #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
# publisher: 1010094929028825 #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'

# Email subscriptions
mailchimp: https://identex.us2.list-manage.com/subscribe/post?u=f61e0d82c2f05f7d1ff4b1184&amp;id=12d985485a # the link of the embed signup form generated from mailchimp into the html code of the embed form

#addthis: //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5a5ba11b28ce5032

# PERSONAL SCRIPTS LOADED GLOBALLY
# cripts: 
#   css: ''
#   js: ''


#algolia:
#  application_id: 'GU8HT2BGPU'
#  index_name:     'your_index_name' # I'm looking to understand how it can be set the index_name of agolia https://www.algolia.com/apps/GU8HT2BGPU/dashboard and https://community.algolia.com/jekyll-algolia/getting-started.html

#cloudinary:
#  cloud_name: officialtrento #  NOT WORK FOR NOW from the cloudinary-jekyll plugin guide https://nhoizey.github.io/jekyll-cloudinary/#installation
#  presets:
#  default:
#    min_width: 320
#    max_width: 1600
#    fallback_max_width: 800
#    steps: 5
#    sizes: "(min-width: 50rem) 50rem, 90vw"

# Build settings
markdown: kramdown

#theme: minima
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap

#gems:
#  - amp-jekyll

#ampdir: amp



# Gallery section (https://jorigami.github.io/gallery)

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/identex
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/identex.co
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/identexco




gallery-title: identex
gallery-description: >- # this means to ignore newlines until "baseurl:"
  The gallery section of the identex knowledge base.



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
